
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sat May 09 19:57:56 ICT 2020
//----------------------------------------------------

package src;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DIVIDE = 5;
  public static final int STRING_LITERAL = 38;
  public static final int LTE = 17;
  public static final int CHAR = 23;
  public static final int CHAR_LITERAL = 37;
  public static final int NOTEQUAL = 20;
  public static final int LPAREN = 11;
  public static final int SEMI = 10;
  public static final int INT = 21;
  public static final int MINUS = 3;
  public static final int RPAREN = 12;
  public static final int BOOLEAN_LITERAL = 39;
  public static final int AND = 13;
  public static final int ELSEIF = 30;
  public static final int LT = 15;
  public static final int OR = 14;
  public static final int PLUS = 2;
  public static final int IF = 28;
  public static final int EXP = 33;
  public static final int ID = 34;
  public static final int EOF = 0;
  public static final int BOOLEAN = 25;
  public static final int EQUAL = 19;
  public static final int error = 1;
  public static final int LCURLY = 26;
  public static final int MOD = 6;
  public static final int EQ = 7;
  public static final int GTE = 18;
  public static final int RCURLY = 27;
  public static final int TIMES = 4;
  public static final int ELSE = 29;
  public static final int WHILE = 31;
  public static final int FLOAT = 22;
  public static final int STRING = 24;
  public static final int FLOAT_LITERAL = 36;
  public static final int GT = 16;
  public static final int NOPRINT = 8;
  public static final int PRINT = 9;
  public static final int DO = 32;
  public static final int INTEGER_LITERAL = 35;
}

